name: Publish
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'What version? Version can be: patch | minor | major | prepatch | preminor | premajor | prerelease | 1.2.3'
        required: true
        default: 'patch'

env:
  GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: git config --global user.name ${{ github.actor }}
      - run: git config --global user.email ''
      - run: npm ci
      - run: npm run lint
      - run: npm run release